# Generated by Django 5.1.7 on 2025-03-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Restaurant',
        ),
    ]
