# Generated by Django 5.1.7 on 2025-04-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_room_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRestaurant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'api_restaurants',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
