# Generated by Django 5.1.7 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apirestaurant_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('surname', models.CharField(blank=True, max_length=55, null=True)),
                ('password', models.CharField(db_collation='utf8mb4_bin', max_length=255)),
                ('email', models.CharField(db_collation='utf8mb4_bin', max_length=255, unique=True)),
                ('status', models.CharField(max_length=8)),
                ('created_at', models.DateField()),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'clients',
                'db_table_comment': 'Tabela do przechowywania dane do logowania o kliencie oraz jeog status, czy jest on zablokowany czy nie. Defaultowo u┐ytkownicy s╣ zablokowani, po zatwierdzeniu maila s╣ oni odblokowywani.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorites',
                'db_table_comment': 'Tabela przechowuja informacj na  temat ulubionych restauracji klienta.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.IntegerField(blank=True, null=True)),
                ('success', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'db_table_comment': "Tabela przechowuca informacje na temat prb logowania si uytkownikw, zawiera informacje tj. client_id, czas prby logowania, oraz czy udao si zalogowa (jeli jest '1' tzn.  si nie udao, a jeli '0' - udao si zalogowa pomlnie).",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preferences',
                'db_table_comment': 'Tabela zawierajca preferencje utkownikw. Posiada pola tj. typ kuchni oraz lokalizacja.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'ratings',
                'db_table_comment': 'Tablica przechowujca informacje na temat ocen z restauracji. Zawiera informacje na temat wartoci oceny (1.0-5.0) pobytu w restauracji, komentarz oraz dat utworzenia. Jest ona poczona z restauracj, ktra jet oceniana oraz klient, ktry wystawi ocen.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('cuisine', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
            ],
            options={
                'db_table': 'restaurants',
                'db_table_comment': 'Tabela zawierajca informacje na temat restauracji. Podajemy  w niej nazwŕ restauracji, lokalizacjŕ, gwny typ kuchni jaki serwuj, zdjcie restauracji oraz link do zewntrznej strony restauracji.',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='apirestaurant',
            table='api_restaurant',
        ),
    ]
